export const genres: string[] = [
  "Deception -- Juvenile fiction.",
  "Poets -- Fiction.",
  "Potter, Harry (Fictitious character) -- Juvenile fiction.",
  "Strawberries -- Folklore.",
  "Fear.",
  "Metamorphosis.",
  "Play -- Juvenile fiction.",
  "Cats.",
  "Dentists.",
  "Self-confidence -- Fiction.",
  "Cinderella (Legendary character)",
  "Folklore -- United States.",
  "JUVENILE FICTION -- Animals -- Pigs.",
  "Korea -- History -- Koryŏ period, 935-1392 -- Fiction.",
  "Women -- Biography.",
  "Middle schools -- Juvenile fiction.",
  "Humorous fiction.",
  "Individuality.",
  "Agricultural laborers.",
  "Poetry.",
  "Animals -- Juvenile fiction.",
  "Swine.",
  "Sprinting -- Juvenile fiction.",
  "Missing persons -- Fiction.",
  "Middle schools.",
  "Camps -- Juvenile fiction.",
  "Artists.",
  "Immigrants -- United States -- Biography.",
  "Olivia (Fictitious character from Falconer)",
  "Moon.",
  "Buses -- Juvenile fiction.",
  "Monsters -- Fiction.",
  "JUVENILE FICTION -- Animals -- Wolves & Coyotes.",
  "Household employees -- Fiction.",
  "Boys -- Africa -- Juvenile fiction.",
  "Voyages and travels -- Fiction.",
  "Cerebral palsy -- Fiction.",
  "Toads -- Juvenile fiction.",
  "Conduct of life -- Juvenile fiction.",
  "Korea -- History -- Koryŏ period, 935-1392 -- Juvenile fiction.",
  "Folklore -- Tanzania -- Serengeti National Park -- Pictorial works.",
  "Fatherless families.",
  "Intellect -- Juvenile fiction.",
  "Time travel -- Fiction.",
  "Cats -- Fiction.",
  "Toilet training -- Juvenile literature.",
  "Death -- Fiction.",
  "Novels in verse.",
  "Lighthouses -- New York (State) -- New York -- Fiction.",
  "Prince Edward Island -- Fiction.",
  "Japan -- Fiction.",
  "Winnie-the-Pooh (Fictitious character) -- Fiction.",
  "Siblings -- Juvenile fiction.",
  "Strikes and lockouts -- Juvenile fiction.",
  "Pride and vanity.",
  "Zeus (Greek deity)",
  "Fathers and daughters -- Juvenile fiction.",
  "History.",
  "Humorous stories, English.",
  "Trust -- Juvenile fiction.",
  "Black Panther Party -- Juvenile fiction.",
  "Railroad trains -- Fiction.",
  "Metropolitan Museum of Art (New York, N.Y.) -- Fiction.",
  "Steampunk fiction.",
  "Self-acceptance -- Fiction.",
  "Strikes and lockouts.",
  "Diaries -- Fiction.",
  "Bell, Cece -- Comic books, strips, etc.",
  "Fear -- Fiction.",
  "World War, 1939-1945 -- Denmark -- Juvenile fiction.",
  "Mothers.",
  "Sex role -- Juvenile fiction.",
  "Oakland (Calif.) -- History -- 20th century -- Juvenile fiction.",
  "Japanese Americans -- Fiction.",
  "Juvenile delinquency.",
  "Toes.",
  "Princes -- Juvenile fiction.",
  "Alphabet -- Juvenile fiction.",
  "School principals -- Fiction.",
  "Oakland (Calif.) -- History -- 20th century -- Fiction.",
  "Space and time -- Fiction.",
  "New York (N.Y.) -- History -- 1951- -- Juvenile fiction.",
  "Autobiographies.",
  "Homesickness -- Fiction.",
  "Defecation -- Juvenile literature.",
  "Biographical fiction.",
  "Animal welfare -- Juvenile fiction.",
  "Food habits -- Fiction.",
  "Mexican Americans.",
  "Lion.",
  "Tricksters -- Juvenile fiction.",
  "Wolves.",
  "Juvenile literature -- Picture books.",
  "YOUNG ADULT FICTION -- Romance.",
  "Snow -- Juvenile fiction.",
  "World Trade Center (New York, N.Y. : 1970-2001)",
  "Dogs -- Juvenile fiction.",
  "France -- Paris.",
  "Wolves -- Juvenile fiction.",
  "Emigration and immigration -- Fiction.",
  "Monkeys -- Fiction.",
  "Missing persons -- Juvenile fiction.",
  "Robots.",
  "Avarice.",
  "Mice -- Juvenile literature.",
  "Teenage boys -- Juvenile fiction.",
  "Chinese Americans -- Fiction.",
  "Cinderella (Legendary character) -- Juvenile fiction.",
  "Bullfights -- Juvenile fiction.",
  "Spain -- Juvenile fiction.",
  "Hats.",
  "Girls -- Comic books, strips, etc. -- Juvenile fiction.",
  "Friendship -- Juvenile fiction.",
  "England -- Fiction.",
  "JUVENILE FICTION -- Family -- Multigenerational.",
  "Authors -- Fiction.",
  "Rules -- Fiction.",
  "Camps.",
  "Circus animals -- Juvenile fiction.",
  "JUVENILE FICTION -- Humorous Stories.",
  "Single-parent families -- Fiction.",
  "Basketball -- Fiction.",
  "Homeless persons.",
  "Lightning in literature.",
  "Gratitude -- Juvenile fiction.",
  "Dogs.",
  "Peach -- Fiction.",
  "Friendship in children -- Juvenile fiction.",
  "Families.",
  "American poetry.",
  "African American girls.",
  "JUVENILE FICTION -- Science Fiction.",
  "Florida -- Juvenile fiction.",
  "Mice.",
  "Sisters -- Fiction.",
  "Women painters -- Juvenile fiction.",
  "Superior, Lake, Region -- Fiction.",
  "Toes -- Fiction.",
  "Orphans -- Fiction.",
  "Korean Americans -- Fiction.",
  "Fishes.",
  "Mystery and detective stories.",
  "Parent and child -- Juvenile fiction.",
  "Betrayal.",
  "Princes.",
  "Indians of North America -- Folklore.",
  "Mothers -- Juvenile fiction.",
  "Beaches -- Juvenile fiction.",
  "Behavior -- Fiction.",
  "Flint (Mich.) -- Fiction.",
  "Logan family (Fictitious characters : Taylor) -- Fiction.",
  "Folklore -- China.",
  "Rickshaws -- Juvenile fiction.",
  "Escapes -- Juvenile fiction.",
  "Méliès, Georges, 1861-1938 -- Fiction.",
  "Mice -- Juvenile fiction.",
  "Rabbits -- Juvenile fiction.",
  "Tales -- United States.",
  "Cooperativeness -- Juvenile fiction.",
  "Juvenile works.",
  "Friendship.",
  "Juvenile materials.",
  "Brothers -- Juvenile fiction.",
  "Cooperation -- Juvenile literature.",
  "Families -- Fiction.",
  "African American families -- Juvenile fiction.",
  "Fishes -- Fiction.",
  "Black Panther Party -- Fiction.",
  "Anatomy.",
  "Woodson, Jacqueline -- Juvenile poetry.",
  "Puppets -- Fiction.",
  "Cartoonists -- Biography -- Comic books, strips, etc.",
  "Circus -- Juvenile fiction.",
  "Cherokee Indians -- Folklore.",
  "Jealousy -- Juvenile fiction.",
  "Children -- Conduct of life.",
  "Intergenerational relations.",
  "Fathers and sons -- Fiction.",
  "Girls -- China -- Juvenile fiction.",
  "Grandfathers -- Juvenile fiction.",
  "Zoo animals -- Fiction.",
  "Bell, Cece -- Cartoons and comics.",
  "JUVENILE FICTION / Mysteries & Detective Stories.",
  "Spy fiction.",
  "Teddy bears -- Fiction.",
  "Animals.",
  "Liberty -- Juvenile fiction.",
  "Street life.",
  "Wilderness survival -- Fiction.",
  "Drawing -- Fiction.",
  "Women -- Biography -- Cartoons and comics.",
  "Theft.",
  "Cooperativeness.",
  "Butterflies.",
  "Picture books.",
  "YOUNG ADULT FICTION -- Classics.",
  "Abnormalities, Human -- Fiction.",
  "Birmingham (Ala.) -- Fiction.",
  "Animal sounds.",
  "England -- Juvenile fiction.",
  "New York (N.Y.) -- History -- 1951- -- Fiction.",
  "Wishes.",
  "Home.",
  "Hispanic Americans -- Juvenile fiction.",
  "Gorilla -- Fiction.",
  "Generosity -- Fiction.",
  "Puppets -- Juvenile fiction.",
  "Jungles -- Juvenile fiction.",
  "Elephants -- Juvenile fiction.",
  "West Africa.",
  "Reasoning.",
  "City and town life -- Florida -- Juvenile fiction.",
  "Color -- Juvenile fiction.",
  "Diaries -- Juvenile fiction.",
  "Prejudices -- Fiction.",
  "Toys -- Juvenile fiction.",
  "Magic.",
  "Mexican Americans -- California -- Juvenile fiction.",
  "Penguins -- Fiction.",
  "Outer space -- Comic books, strips, etc. -- Juvenile fiction.",
  "Cooperativeness -- Fiction.",
  "Little Red Riding Hood (Tale)",
  "Flight -- Fiction.",
  "Witches -- Juvenile fiction.",
  "Drawing -- Juvenile fiction.",
  "Outer space.",
  "African Americans -- Folklore.",
  "JUVENILE FICTION -- Animals -- Cats.",
  "Cameras -- Juvenile fiction.",
  "Paris (France) -- History -- 1870-1940 -- Fiction.",
  "Good and evil.",
  "African American folk art -- Juvenile fiction.",
  "Familial behavior in animals -- Fiction.",
  "Florida -- Fiction.",
  "Space and time -- Juvenile fiction.",
  "People with disabilities -- Fiction.",
  "Young adult works.",
  "Good and evil -- Juvenile fiction.",
  "African Americans -- Fiction",
  "Piggie (Fictitious character : Willems) -- Juvenile fiction.",
  "Novels.",
  "School integration -- United States -- Juvenile literature.",
  "Toys -- Fiction.",
  "Socialization.",
  "Stories in rhyme.",
  "Anatomy -- Juvenile literature.",
  "Basketball stories.",
  "Wishes -- Juvenile fiction.",
  "Sisters.",
  "Swine -- Juvenile fiction.",
  "Monsters -- Juvenile fiction.",
  "City and town life -- Florida -- Fiction.",
  "Fingers.",
  "Nineteen seventies -- Juvenile fiction.",
  "Elephants.",
  "Chairs -- Fiction.",
  "Gifted children -- Fiction.",
  "Parent and child.",
  "Self-confidence -- Juvenile fiction.",
  "Villages -- Africa -- Juvenile fiction.",
  "Civil rights movements -- United States -- History -- 20th century -- Juvenile literature.",
  "Snowballs.",
  "Fathers and daughters.",
  "Peddling -- Fiction.",
  "Animals -- Tanzania -- Serengeti National Park -- Pictorial works.",
  "Animals -- Infancy.",
  "New York (State) -- New York.",
  "Dreams.",
  "Airplane crash survival.",
  "Wizards -- Juvenile fiction.",
  "JUVENILE FICTION -- Health & Daily Living -- Diseases, Illnesses & Injuries.",
  "Spain.",
  "Cows -- Fiction.",
  "Abnormalities, Human.",
  "Zimbabwe -- Juvenile fiction.",
  "Nose -- Fiction.",
  "Immigrants.",
  "Friendship in children.",
  "Manhattan (New York, N.Y.) -- Juvenile fiction.",
  "Children with disabilities -- Juvenile fiction.",
  "Zoo keepers -- Fiction.",
  "African American folk art.",
  "Mythology, Greek -- Fiction.",
  "Buried treasure -- Fiction.",
  "Country life -- Prince Edward Island -- Fiction.",
  "California.",
  "Toes -- Juvenile fiction.",
  "Adventure and adventurers -- Juvenile fiction.",
  "Witches.",
  "Olivia (Fictitious character from Falconer) -- Juvenile fiction.",
  "JUVENILE FICTION -- Comics & Graphic Novels.",
  "Hats -- Juvenile fiction.",
  "Heroes -- Fiction.",
  "Railroad stations.",
  "Trust.",
  "Dogs -- Fiction.",
  "JUVENILE FICTION / Family / Siblings.",
  "Deaf children -- Comic books, strips, etc.",
  "Self-acceptance.",
  "Communication -- Fiction.",
  "Hearing aids for children -- Comic books, strips, etc.",
  "Home -- Juvenile fiction.",
  "First day of school -- Fiction.",
  "Children -- Attitudes -- Juvenile fiction.",
  "Animals -- Folklore.",
  "Doors -- Fiction.",
  "Betrayal -- Juvenile fiction.",
  "Newbery Medal: Winner -- 2013.",
  "Woodson, Jacqueline.",
  "Typewriters.",
  "Animals -- Treatment -- Fiction.",
  "Mosquitoes.",
  "Obedience -- Juvenile fiction.",
  "Treasure troves -- Juvenile fiction.",
  "JUVENILE FICTION -- Comics & Graphic Novels -- Science Fiction.",
  "Lion -- Juvenile fiction.",
  "Examinations -- Fiction.",
  "African Americans -- Civil rights -- History -- 20th century -- Juvenile poetry.",
  "Obedience.",
  "Mississippi -- Race relations -- Fiction.",
  "Automobiles -- Juvenile fiction.",
  "Peddlers -- Fiction.",
  "Colors -- Fiction.",
  "Adventure and adventurers.",
  "Concord (Mass.) -- Juvenile fiction.",
  "Names, Personal -- Fiction.",
  "Individuality -- Juvenile fiction.",
  "Gluttony.",
  "Fire engines -- Fiction.",
  "Butterflies -- Juvenile fiction.",
  "Lion -- Juvenile literature.",
  "Typewriters -- Fiction.",
  "Humorous poetry, American.",
  "Students.",
  "Authors, American -- Biography -- Juvenile literature.",
  "Drew, Nancy (Fictitious character) -- Juvenile fiction.",
  "Magic -- Juvenile fiction.",
  "Elephants -- Fiction.",
  "Metamorphosis -- Juvenile fiction.",
  "Humorous stories.",
  "Young adult fiction.",
  "Comics and cartoons.",
  "Private schools -- New York (State) -- New York -- Juvenile fiction.",
  "Canada.",
  "Chinese Americans -- Juvenile fiction.",
  "Frogs -- Juvenile fiction.",
  "Juvenile detention -- Juvenile fiction.",
  "Harlem (New York, N.Y.) -- Social life and customs -- 20th century -- Juvenile fiction.",
  "JUVENILE FICTION / People & Places / United States / Asian American.",
  "Ojibwa Indians -- Fiction.",
  "Children's stories.",
  "Potter, Harry (Fictitious character) -- Fiction.",
  "Lost articles -- Juvenile fiction.",
  "Tales -- Tanzania -- Serengeti National Park -- Pictorial works.",
  "Writing -- Juvenile fiction.",
  "Domestic animals -- Juvenile fiction.",
  "Grandmothers.",
  "Preteens.",
  "Buses -- Fiction",
  "Prejudices -- Juvenile fiction.",
  "Harlem (New York, N.Y.) -- Juvenile fiction.",
  "Self-confidence.",
  "Blues poetry.",
  "Animals -- Infancy -- Fiction.",
  "Liberty.",
  "Manners and customs.",
  "Space and time.",
  "Siblings.",
  "Fear -- Juvenile fiction.",
  "Cattle -- Juvenile fiction.",
  "Times Square (New York, N.Y.) -- Fiction.",
  "Typewriters -- Juvenile fiction.",
  "Bangladesh -- Social life and customs -- Juvenile fiction.",
  "Grandfathers -- Fiction.",
  "Students -- Juvenile fiction.",
  "Snowballs -- Juvenile fiction.",
  "Divorce -- Fiction.",
  "Soups -- Fiction.",
  "Family life -- Fiction.",
  "Infants.",
  "Gardening -- Fiction.",
  "African American civil rights workers.",
  "Buses.",
  "Identity -- Fiction.",
  "United States -- Description and travel -- Fiction.",
  "Friendship -- Fiction.",
  "Fathers and sons -- Juvenile fiction.",
  "JUVENILE FICTION -- Historical -- United States -- 20th Century.",
  "World War, 1939-1945 -- Denmark -- Fiction.",
  "Harlem (New York, N.Y.) -- Juvenile poetry.",
  "Transportation -- Fiction.",
  "Emotional problems -- Fiction.",
  "France -- History -- Third Republic, 1870-1940 -- Fiction.",
  "Hotels, motels, etc. -- Fiction.",
  "Carrots -- Fiction.",
  "Wizards -- Fiction.",
  "Children's poetry, American.",
  "Cerebral palsy -- Juvenile fiction.",
  "Fingers -- Fiction.",
  "Runners (Sports) -- Juvenile fiction.",
  "Pottery -- Fiction.",
  "Cows -- Juvenile fiction.",
  "Poseidon (Greek deity) -- Juvenile fiction.",
  "Drummers (Musicians) -- Juvenile fiction.",
  "United States -- Social conditions -- 1960-1980 -- Biography.",
  "Artists -- United States.",
  "Africa -- Juvenile fiction.",
  "Children -- Books and reading -- Juvenile poetry.",
  "Morales, Yuyi -- Juvenile literature.",
  "Race relations -- Fiction.",
  "Peter Rabbit (Fictitious character) -- Fiction.",
  "JUVENILE FICTION -- Animals.",
  "Mexican Americans -- Biography.",
  "Narnia (Imaginary place) -- Juvenile fiction.",
  "Fire engines -- Juvenile fiction.",
  "Schools -- Comic books, strips, etc.",
  "JUVENILE FICTION -- Law & Crime.",
  "Rats -- Fiction.",
  "Spiders -- Fiction.",
  "Orphans -- Juvenile fiction.",
  "Flight.",
  "Diary fiction.",
  "Poseidon (Greek deity)",
  "Hogwarts School of Witchcraft and Wizardry (Imaginary organization) -- Juvenile fiction.",
  "Toy and movable books -- Specimens.",
  "Sharing -- Fiction.",
  "JUVENILE FICTION -- Social Themes -- Self-Esteem & Self-Reliance.",
  "Cinderella (Tale)",
  "Girls.",
  "California -- Juvenile fiction.",
  "Siblings -- Fiction.",
  "Aerialists -- France.",
  "City and town life -- Fiction",
  "Snow.",
  "Gratitude.",
  "African Americans.",
  "Villians -- Fiction.",
  "Toys.",
  "YOUNG ADULT FICTION -- Social Themes -- Friendship.",
  "Imagination -- Juvenile fiction.",
  "Minnows -- Juvenile fiction.",
  "Graphic novels.",
  "Airplane crash survival -- Fiction.",
  "Gluttony -- Juvenile fiction.",
  "Friendship -- Comic books, strips, etc.",
  "Florida.",
  "Gender nonconformity -- Juvenile fiction.",
  "Dragons -- Juvenile fiction.",
  "African American women authors -- Biography -- Juvenile poetry.",
  "Juvenile delinquency -- Juvenile fiction.",
  "Intergenerational relations -- Juvenile fiction.",
  "Jackson, Percy (Fictitious character) -- Juvenile fiction.",
  "Prejudices.",
  "JUVENILE FICTION / Humorous Stories.",
  "Communication -- Juvenile fiction.",
  "Animals, Mythical.",
  "Learning -- Juvenile fiction.",
  "Depressions -- 1929 -- Fiction.",
  "New York (State) -- New York -- Manhattan.",
  "France -- Folklore.",
  "African American girls -- Juvenile fiction.",
  "Play.",
  "JUVENILE FICTION / Action & Adventure.",
  "African American artists.",
  "Indians of North America -- Superior, Lake, Region -- Fiction.",
  "JUVENILE FICTION -- Animals -- Elephants.",
  "Homeless persons -- Juvenile fiction.",
  "Caterpillars -- Fiction.",
  "Stealing -- Fiction.",
  "Families -- Juvenile fiction.",
  "Historical fiction.",
  "Human-alien encounters -- Comic books, strips, etc. -- Juvenile fiction.",
  "Kings and rulers.",
  "Moon -- Fiction.",
  "Materialism -- Juvenile fiction.",
  "Mothers -- Fiction.",
  "City and town life -- Juvenile fiction.",
  "Runaway children -- Fiction.",
  "Caterpillars.",
  "African American artists -- Juvenile poetry.",
  "Virginia -- History -- 20th century -- Fiction.",
  "Folklore -- Africa, West.",
  "JUVENILE FICTION -- Social Themes -- Special Needs.",
  "Middle schools -- Fiction.",
  "Comic books, strips, etc. -- United States.",
  "Narnia (Imaginary place)",
  "Railroad stories.",
  "World War, 1939-1945 -- Jews -- Rescue -- Fiction.",
  "Interpersonal relations -- Juvenile fiction.",
  "Picture books for children.",
  "JUVENILE FICTION -- Action & Adventure.",
  "Poets -- Juvenile fiction.",
  "Aardvark -- Fiction.",
  "Bulls -- Fiction.",
  "Theft -- Juvenile fiction.",
  "Veterinarians -- Juvenile fiction.",
  "Snow -- Fiction.",
  "Aslan the Lion (Fictitious character) -- Fiction.",
  "Railroad stations -- France -- Paris -- Juvenile fiction.",
  "Imagination.",
  "Paranormal fiction.",
  "JUVENILE FICTION -- People & Places -- United States -- African American.",
  "Civil rights movements -- Fiction.",
  "Immigrants -- United States -- Biography -- Juvenile literature.",
  "Deaf -- United States -- Biography -- Comic books, strips, etc.",
  "Wit and humor, Juvenile.",
  "High interest-low vocabulary books.",
  "Authors -- Cartoons and comics.",
  "Fantasy fiction.",
  "Hispanic Americans -- Civil rights -- Juvenile literature.",
  "Desire.",
  "United States -- Social conditions -- 1960-1980 -- Juvenile poetry.",
  "Africa.",
  "JUVENILE FICTION -- Fairy Tales & Folklore -- Country & Ethnic.",
  "Healing.",
  "Schools -- Juvenile fiction.",
  "Flight -- Juvenile fiction.",
  "Railroad stations -- Fiction.",
  "Deception.",
  "Animal sounds -- Fiction.",
  "Jews -- Folklore.",
  "Homesickness -- Juvenile fiction.",
  "Mendez, Sylvia, 1936- -- Childhood and youth -- Juvenile literature.",
  "Brothers -- Fiction.",
  "Hats -- Fiction.",
  "YOUNG ADULT FICTION -- Fantasy.",
  "Crickets -- Fiction.",
  "Mice -- Fiction.",
  "Seasons -- Fiction.",
  "Defecation.",
  "JUVENILE FICTION / Social Themes / Friendship.",
  "African American families.",
  "New York (State) -- New York -- Harlem.",
  "Mermaids -- Juvenile fiction.",
  "Reasoning -- Juvenile fiction.",
  "Genius -- Fiction.",
  "Teenage boys.",
  "Comics (Graphic works)",
  "Hades (Greek deity) -- Juvenile fiction.",
  "Cats -- Juvenile fiction.",
  "Bulls.",
  "Twins -- Fiction.",
  "Piggie (Fictitious character : Willems)",
  "Infants -- Juvenile fiction.",
  "Fathers and sons.",
  "Dentists -- Juvenile fiction.",
  "Strikes and lockouts -- Fiction.",
  "African Americans -- Civil rights -- History -- 20th century -- Biography.",
  "Twins -- Juvenile fiction.",
  "Tricksters.",
  "Color -- Fiction.",
  "Mythology, Greek.",
  "JUVENILE FICTION -- Social Themes -- New Experience.",
  "JUVENILE FICTION -- Fantasy & Magic.",
  "Desire -- Juvenile fiction.",
  "Allegories.",
  "Concord (Mass.) -- Fiction.",
  "JUVENILE FICTION -- School & Education.",
  "Abnormalities, Human -- Juvenile fiction.",
  "Paris -- Fiction.",
  "Orphans.",
  "Grandmothers -- Juvenile fiction.",
  "Moon -- Juvenile fiction.",
  "Identity (Psychology) in children -- Juvenile poetry.",
  "Avarice -- Juvenile fiction.",
  "Gerald (Fictitious character : Willems)",
  "United States -- Description and travel -- Juvenile fiction.",
  "Inventors.",
  "Hades (Greek deity) -- Fiction.",
  "Schools.",
  "Fingers -- Juvenile fiction.",
  "Japanese Americans -- Juvenile fiction.",
  "Sisters -- Juvenile fiction.",
  "Genius -- Juvenile fiction.",
  "Science fiction.",
  "Chinese Americans.",
  "Hades (Greek deity)",
  "Witches -- Fiction.",
  "Counting -- Juvenile fiction.",
  "Preteens -- Juvenile fiction.",
  "African American civil rights workers -- Juvenile poetry.",
  "Fiction.",
  "Divorce -- Juvenile fiction.",
  "Dentists -- Fiction.",
  "Materialism.",
  "Harlem (New York, N.Y.) -- Fiction.",
  "Private schools.",
  "Self-acceptance -- Juvenile fiction.",
  "Tales.",
  "African Americans -- Juvenile fiction.",
  "Méliès, Georges, 1861-1938.",
  "Mythology, Greek -- Juvenile fiction.",
  "Paris (France) -- History -- Fiction.",
  "Veterinarians.",
  "Poseidon (Greek deity) -- Fiction.",
  "Inventors -- Comic books, strips, etc. -- Juvenile fiction.",
  "Courage -- Juvenile fiction.",
  "Harlem (New York, N.Y.) -- Poetry.",
  "Jackson, Percy (Fictitious character)",
  "Nineteen seventies.",
  "Visual perception.",
  "Animals, Mythical -- Juvenile fiction.",
  "Undercover operations -- Fiction.",
  "Voyages and travels -- Juvenile fiction.",
  "Feces.",
  "Feces -- Juvenile literature.",
  "Dance music -- Juvenile fiction.",
  "Petit, Philippe, 1949-",
  "Humorous poetry.",
  "Minnows.",
  "Authors, American -- Biography -- Comic books, strips, etc.",
  "Toilet training.",
  "China.",
  "Treasure troves.",
  "Street life -- Juvenile fiction.",
  "Cows.",
  "Jealousy.",
  "Quakers.",
  "Wilderness survival.",
  "Wordless picture books.",
  "Aslan the Lion (Fictitious character) -- Juvenile fiction.",
  "Identity (Psychology) in children -- Biography.",
  "Strega Nona (Fictitious character)",
  "Action and adventure fiction.",
  "City and town life.",
  "Gerald (Fictitious character : Willems) -- Juvenile fiction.",
  "Folklore -- Italy.",
  "JUVENILE FICTION -- Animals -- Fishes.",
  "Lightning in literature -- Juvenile fiction.",
  "Jungle animals -- Juvenile fiction.",
  "African Americans -- Juvenile poetry.",
  "Magic -- Fiction.",
  "Children -- Attitudes.",
  "Board books.",
  "Lost articles.",
  "Conduct of life.",
  "Girls -- Juvenile fiction.",
  "Children's stories, English.",
  "African Americans -- Poetry.",
  "Counting.",
  "Pride and vanity -- Juvenile fiction.",
  "Amelia-Bedelia (Fictitious character) -- Juvenile fiction.",
  "Africa -- Fiction.",
  "Robots -- Fiction.",
  "Interpersonal relations -- Fiction.",
  "Bullfights.",
  "JUVENILE FICTION -- Family.",
  "Spain -- Fiction.",
  "Robots -- Comic books, strips, etc. -- Juvenile fiction.",
  "School children -- Juvenile fiction.",
  "Short stories.",
  "Immigrants -- Juvenile fiction.",
  "JUVENILE FICTION -- Mysteries & Detective Stories.",
  "Animal sounds -- Juvenile fiction.",
  "School stories.",
  "Canada -- Fiction.",
  "Biography.",
  "Rabbits -- Fiction.",
  "Gifted children -- Juvenile fiction.",
  "Bell, Cece -- Childhood and youth -- Comic books, strips, etc.",
  "Denmark -- Juvenile fiction.",
  "Intellect.",
  "Swine -- Fiction.",
  "Grandmothers -- Fiction",
  "Denmark -- Fiction.",
  "Fairy tales.",
  "Extraterrestrial beings.",
  "Mosquitoes -- Folklore.",
  "African Americans -- Fiction.",
  "Caterpillars -- Juvenile fiction.",
  "Deaf -- Cartoons and comics.",
  "Food habits -- Juvenile fiction.",
  "Agricultural laborers -- Juvenile fiction.",
  "Film -- Fiction.",
  "Bedtime -- Fiction.",
  "Horror fiction.",
  "Civil rights movements -- Juvenile fiction.",
  "Domestic animals.",
  "France -- History -- Fiction.",
  "Extraterrestrial beings -- Comic books, strips, etc. -- Juvenile fiction.",
  "New York (N.Y.) -- History -- 20th century -- Juvenile fiction.",
  "Children -- Conduct of life -- Juvenile fiction.",
  "Divorce.",
  "Children.",
  "Zeus (Greek deity) -- Fiction.",
  "Japan -- Social life and customs -- Juvenile fiction.",
  "Dreams -- Juvenile fiction.",
  "African American girls -- Juvenile poetry.",
  "Children -- Juvenile fiction.",
  "Massachusetts -- Concord.",
  "Corduroy (Fictitious character) -- Fiction.",
  "Mexican Americans -- Biography -- Juvenile literature.",
  "United States.",
  "Fishes -- Juvenile fiction.",
  "Zeus (Greek deity) -- Juvenile fiction.",
  "Children -- Books and reading -- Biography.",
  "Linsky, Jenny (Fictitious character) -- Juvenile fiction.",
  "Méliès, Georges, 1861-1938 -- Juvenile fiction.",
  "Folklore.",
  "Bulls -- Juvenile fiction.",
  "Survival -- Fiction.",
  "Zimbabwe.",
  "Africa -- Pictorial works -- Juvenile literature.",
  "Black author.",
  "Fables, African.",
  "Juvenile detention.",
  "Toy and movable books.",
  "Stories without words.",
  "Blind -- Books and reading.",
  "Deaf -- United States -- Biography -- Juvenile literature.",
  "Readers.",
  "Escapes.",
  "Schools -- Fiction.",
  "Tightrope walking.",
  "Kings and rulers -- Juvenile fiction.",
  "Badgers -- Fiction.",
  "Islands -- Fiction.",
  "Saving and investment -- Fiction.",
  "Cattle.",
  "Secret societies -- Fiction.",
  "Morales, Yuyi.",
  "Homosexuality -- Fiction.",
  "Gorilla -- Juvenile fiction.",
  "Animals -- Infancy -- Juvenile fiction.",
  "Dragons -- Fiction.",
  "Human-alien encounters.",
  "China -- Juvenile fiction.",
  "Shirley, Anne (Fictitious character) -- Fiction.",
  "Fatherless families -- Juvenile fiction.",
  "Babies -- Fiction.",
  "Animals -- Fiction.",
  "Diaries.",
  "JUVENILE FICTION -- Fairy Tales & Folklore -- Adaptations.",
  "Pigs -- Fiction.",
  "Doors -- Juvenile fiction.",
  "Robots -- Juvenile fiction.",
  "Bell, Cece -- Juvenile literature.",
  "Science fiction comics.",
  "Hispanic Americans -- Education -- Juvenile literature.",
  "Domestic animals -- Fiction.",
];
